# Generated by Django 5.0.6 on 2024-06-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customuser_profile_pic_alter_image_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsecomment',
            old_name='comment',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='responsecomment',
            old_name='post',
            new_name='post_id',
        ),
    ]
