# Generated by Django 5.0.6 on 2024-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_comment_responsecomment_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, default='user', max_length=1000),
        ),
    ]
