# Generated by Django 5.0.6 on 2024-06-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsecomment',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
