# Generated by Django 5.0.6 on 2024-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tag_color_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
