# Generated by Django 5.0.6 on 2024-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_customuser_is_first_login_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
