# Generated by Django 5.0.6 on 2024-06-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_customuser_certified_customuser_verfied_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='certified',
            new_name='is_certified',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='verfied',
            new_name='is_verfied',
        ),
    ]
