# Generated by Django 5.0.6 on 2024-06-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_likecommentresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
